=== watuLammini/protestMap/production/backend-server/placesInputSchema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "http://localhost:3000/placesInputSchema.json",
  "title": "Protest movements with a place",
  "description": "Protest movements with a place",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "movementName": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "links": {
        "type": "array",
        "items": { "type": "string" }
      },
      "startYear": {
        "type": [ "number", "null" ]
      },
      "endYear": {
        "type": [ "number", "null" ]
      },
      "placeName": {
        "type": "string"
      },
      "latitude": {
        "type": "number"
      },
      "longitude": {
        "type": "number"
      }
    },
    "required": ["movementName", "placeName", "latitude", "longitude"],
    "additionalProperties": false
  }
}

=== watuLammini/protestMap/inputData/Senegal_Süd Afrika_Kongo.json
[ 
{
"movementName": "Yén a Marre - Wir haben es satt", 
"placeName": "Senegal",
"latitude": 14.497401,
"longitude": -14.452362,
"description": "Die Jugendbewegung Y’en a marre entstand im Januar 2011, als der Senegal von einer Krise in der Stromversorgung geplagt wurde. Zusammen mit dem Journalisten Fadel Barro initiierten die Musiker der Hip Hop Gruppe Keur Gui eine Bewegung, deren Forderungen sich anfänglich auf ein Ende der Stromausfälle konzentrierten, aber bald auf soziale Gerechtigkeit und ein Ende der Korruption ausweiteten. Durch Rapp-Songs werden auf Schwachstellen der Regierung aufmerksam gemacht. Der Song Pareel fordert beispielsweise die Menschen auf, einen neuen Präsidenten zu wählen.",
"links": [
"https://www.deutschlandfunkkultur.de/protest-rapper-im-senegal-musiker-die-regime-stuerzen.979.de.html?dram:article_id=441400",
"https://www.boell.de/de/2016/02/23/rapper-protest-und-reformen-wir-koennen-das-schaffen"
],
"startYear": 2011,
"endYear": null
},
{
"movementName": "Studierendenproteste in Süd Afrika",
"placeName": "Süd Afrika",
"latitude": -26.2041028,
"longitude": 28.0473051,
"description": "#rhodesmustfall, #OpenStellenbosch, #BlackStudentMovement, #feesmustfall, #PatriarchyMustFall. Studierende fordern das Ende eurozentrischer Curricula, die Beseitigung kolonialer Statuen, die Umbenennung von Gebäuden, die Politiker der Apartheid ehrten, und die Diversifizierung des noch immer hauptsächlich weißen und männlichen Lehrkörpers. Sie wollten eine neue Universitätskultur – eine, die nicht nur gleiche Chancen auf Bildung versprach, sondern auch Zugang und Teilhabe für alle. Dabei fordern sie auch eine Senkung der Studiengebühren.",
"links": [
"https://www.zeit.de/kultur/2016-01/suedafrika-studenten-proteste-johannesburg-10nach8/seite-2",
"https://www.spiegel.de/lebenundlernen/uni/suedafrikas-neue-apartheid-schwarze-studenten-wehren-sich-a-1079180.html",
"https://www.yaez.de/schule/diskriminierung-in-suedafrika-schuelerinnen-kaempfen-fuer-ihren-afro/"
]
},
{
"movementName": "La Lucha",
"placeName": "Demokratischen Republik Kongo",
"latitude":  -0.228021,
"longitude": 15.827659,
"description": "Lucha steht für „Lutte pour le changement“, Kampf für Veränderung, und ist mit Protesten gegen staatliche Korruption und Vernachlässigung bekannt geworden.",
"links": [
"https://www.fluter.de/junge-Widerstandsbewegung-Lucha-im-Kongo",
"https://info.arte.tv/de/rdcongo-praesidentschaftswahl-kabila-frist-verstrichen"
]
}
]

=== watuLammini/protestMap/production/inputData/Black Lives Matter_Occupay Wallstreet.json
[
  {
    "movementName": "Black Lives Matter",
    "placeName": "USA",
    "latitude": 40.712784,
    "longitude": -74.005941,
    "description": "ist eine internationale Bewegung, die innerhalb der afroamerikanischen Gemeinschaft in den Vereinigten Staaten entstanden ist und sich gegen Gewalt gegen Schwarze bzw. People of Color einsetzt. Black Lives Matter organisiert regelmäßig Proteste gegen die Tötung Schwarzer durch Polizeibeamte und zu breiteren Problemen wie Racial Profiling, Polizeigewalt und Rassismus.",
    "links": [
      "https://blacklivesmatter.com/",
      "https://www.blacklivesmatterberlin.de/"
    ],
    "startYear": 2013,
    "endYear": null
  },
  {
    "movementName": "Occupy Wallstreet",
    "placeName": "USA",
    "latitude": 40.7830603,
    "longitude": -73.9712488,
    "description": "Occupay Wallstreet ist eine internationale Bewegung, welche sich gegen finanzielle Ungerechtigkeit und die Macht von Banken einsetzte. Die Demonstrant*innen verlangten eine stärkere Kontrolle des Banken- und Finanzsektors durch die Politik, eine Korrektur des als höchst ungerecht empfundenen Steuersystems und eine nachdrückliche Verringerung der Schere zwischen Armen und Reichen.",
    "links": [
      "https://www.bpb.de/politik/wirtschaft/finanzmaerkte/135540/occupy-bewegung?p=0"
    ],
    "startYear": 2011,
    "endYear": 2012
  }
]

=== watuLammini/protestMap/inputData/Svea.json
[
  {
    "movementName": "Grüne Bewegung Iran 2009",
    "placeName": "Tehran",
    "latitude": 35.715298,
    "longitude": 51.404343,
    "description": "Im Juni 2009 demonstrieren Tausende Iranerinnen und Iraner auf den Straßen Teherans. Sie werfen dem Regime vor, die Ergebnisse der Präsidentschaftswahlen 2009 gefälscht zu haben. Das Mullah-Regime reagiert mit Härte auf die Demonstranten. Teheran wird zum Schlachtfeld. Polizisten prügeln auf wehrlose Menschen ein. Es gibt zahlreiche Tote wie die Studentin Neda Agha-Soltan, die durch ihren gewaltsamen Tod zur Ikone der iranischen Widerstandsbewegung wurde.",
    "links": [
      "https://www.planet-wissen.de/kultur/naher_und_mittlerer_osten/die_geschichte_des_irans/pwiediegruenerevolution100.html",
      "https://www.youtube.com/watch?v=QptUELNc1Ls"
    ],
    "startYear": 2009,
    "endYear": 2009
  },
  {
    "movementName": "Iran Protest 2017 bis 2018",
    "placeName": "Tehran",
    "latitude": 35.715298,
    "longitude": 51.404343,
    "description": "Seit Ende Dezember 2017 protestieren Menschen in Iran. Zunächst gingen sie vor allem gegen Armut, Arbeitslosigkeit und die schlechte Versorgungslage auf die Straße. Doch längst richtet sich die Unzufriedenheit gegen das politische System und seine religiöse Ordnung.",
    "links": [
      "https://www.bpb.de/politik/hintergrund-aktuell/262759/proteste-in-iran",
      "https://www.theguardian.com/world/2018/jan/02/iran-protests-how-did-they-start-and-where-are-they-heading"
    ],
    "startYear": 2017,
    "endYear": 2018
  },
  {
    "movementName": "Iran Protest 2019",
    "placeName": "Tehran",
    "latitude": 35.715298,
    "longitude": 51.404343,
    "description": "Die Proteste begannen Mitte November, als die Regierung eine Erhöhung der Benzinpreise bekanntgab. Kraftstoff ist im Iran eigentlich staatlich subventioniert. Die Proteste erreichten bislang nicht das Ausmaß der „grünen Bewegung“ von 2009. Allerdings kam es auch dieses Mal zur Eskalation und zu Gewalt, ähnlich wie bei den Protesten – möglicherweise ein Zeichen für den wachsenden Unmut der Menschen mit ihrer Situation. Ähnliche Demonstrationen gab es bereits zum Jahreswechsel 2018, auch damals bei weitem nicht nur in Teheran.",
    "links": [
      "https://www.deutschlandfunk.de/iran-entsetzen-ueber-brutales-vorgehen-gegen-proteste.2852.de.html?dram:article_id=464954",
      "https://www.hrw.org/de/news/2019/11/19/iran-sicherheitskraefte-schlagen-proteste-nieder"
    ],
    "startYear": 2019,
    "endYear": 2019
  },
  {
    "movementName": "Proteste von Kurd*innen",
    "placeName": "Qamishlo",
    "latitude": 37.054220,
    "longitude": 41.236330,
    "description": "Der Abzug der US-Truppen aus Nordsyrien im Oktober 2019 hat bei vielen Kurden für Bitterkeit gesorgt. In Deutschland, in der Türkei, in Syrien, im Irak oder im Iran kämpfen Kurd*innen um ihre Identität. Der Traum eines eigenen Staates ist in weite Ferne gerückt.",
    "links": [
      "https://www.zdf.de/dokumentation/zdfinfo-doku/die-kurden-unterdrueckung-terrorismus-und-verrat-102.html"
    ],
    "startYear": 2019,
    "endYear": null
  },
  {
    "movementName": "Proteste in Indien gegen sexualisierte Gewalt",
    "placeName": "Neu-Delhi",
    "latitude": 28.632429,
    "longitude": 77.218788,
    "description": "In Indien gibt es immer wieder große Proteste gegen die (sexualisierte) Gewalt an Frauen und Mädchen. So auch 2019 nach der Vergewaltigung und Ermordung einer Tierärztin, sowie eines 6-jährigen Mädchens.",
    "links": [
      "https://www.zeit.de/gesellschaft/zeitgeschehen/2019-12/indien-vergewaltigungen-ermordungen-frauen-protest-demonstrationen",
      "https://timesofindia.indiatimes.com/city/hyderabad/hyderabad-vet-rape-murder-police-seek-custody-of-accusedprotests-continue/articleshow/72335022.cms",
      "https://www.zdf.de/nachrichten/heute/indien-kaempft-fuer-sicherheit-frauen-nach-vergewaltigung-102.html"
    ]
  },
  {
    "movementName": "Gulabi Gang",
    "placeName": "Uttar Pradesh",
    "latitude": 26.846708,
    "longitude": 80.946159,
    "description": "Die Gulabi Gang ist ein Zusammenschluss indischer Frauen im nördlichen Bundesstaat Uttar Pradesh, der sich für Frauenrechte und gegen soziale Ungerechtigkeit einsetzt. Gulabi bedeutet rosa. Die Farbe wird in Indien nicht als feminine Farbe wahrgenommen. Die Gründerin der Gulabi Gang, Sampat Pal Devi, hat diese Farbe nach eigener Aussage gewählt, da sie nicht von einer politischen Gruppe oder Partei verwendet wird. Charakteristisch für die Frauen, die der Gulabi Gang angehören, sind pinkfarbene Saris und Schlagstöcke aus Bambus (Lathi), die üblicherweise von Polizeiangehörigen getragen werden.",
    "links": [
      "https://de.wikipedia.org/wiki/Gulabi_Gang"
    ],
    "startYear": 2006,
    "endYear": null
  }
]

=== watuLammini/protestMap/production/inputData/protestlatinamerica.json
[
	{
	"movementName": "Mapuche",
	"placeName": "südliches Chile und Argentinien",
	"latitude": -38.618190,
	"longitude": -72.328620,
	"description": "Eine indigene Bevölkerungsgruppe im Süden Chiles und Argentiniens, die sich gegen Landnahme zur Wehr setzen. Beginnend mit der Kolonisation durch die spanische Truppen, zeigten sich die Mapuche als widerständig und schafften es vergleichsweise unabhängig von den spanischen Invasoren zu bleiben. Auch heute leisten sie Widerstand gegen Landnahme und Vertreibung. Die natürlichen Ressourcen (Holz, Wasser, Gas) der Regionen in denen die Mapuche leben, sind heute von Ausbeutung durch internationale Konzerne betroffen. Dabei kommen die Aktivist*innen der Mapuche immer wieder in Konflikt mit der chilenischen Polizei, anderen Sicherheitskräften und dem Militär. Bei diesen Auseinandersetzungen kamen schon mehrere Aktivist*innen zu Tode oder wurden schwer verletzt.",
	"links": [
			"https://en.wikipedia.org/wiki/Mapuche_history#Modern_conflict",
			"https://amerika21.de/2020/06/240541/chile-mord-mapuche-carabineros]"
			],
	"startYear": 1541,
	"endYear": null
	},
	{"movementName": "Ni una minos",
	"placeName": "Buenos Aires, Argentinien",
	"latitude": -34.612413,
	"longitude": -58.437077,
	"description": "Benannt nach einer Aussage der mexikanischen Aktivistin Susana Chávez (\"Ni una muerta más\" – \"Keine weitere tote Frau\") formierte sich diese feministische Bewegung im Frühling 2015 in Buenos Aires, Argentinien. Ihre Hauptanliegen ist der Kampf gegen Feminizide (Mord an Frauen) sowie eine Macho-Kultur und beschäftigen sich zusätzlich mit Transgender Rechten, Sexueller Gewalt oder auch Sexarbeit.",
	"links": [
			"https://en.wikipedia.org/wiki/Ni_una_menos",
			"https://amerika21.de/dokument/196483/8-maerz-manifest-frauenstreik"
			],
	"startYear": 2015,
	"endYear": null
	}
]
